esphome:
  name: esphome-web-972b74
  friendly_name: ESP Test
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

interval:
  - interval: 15min
    then:
      - switch.toggle: lm35_power

deep_sleep:
  id: deep_sleep_control
  sleep_duration: 15min

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  fast_connect: true

switch:
  - platform: gpio
    pin: GPIO10
    id: lm35_power
    name: "LM35 Power"
    restore_mode: ALWAYS_OFF
    internal: true
    on_turn_on: 
      then:
        - switch.turn_on: status_led
        - delay: 50ms
        - repeat: 
            count: 50
            then: 
              - component.update: temperature
              - delay: 20ms
    on_turn_off: 
      then:
        - delay: 2s
        - switch.turn_off: status_led
        - if:
            condition:
              - switch.is_off: deep_sleep_checker
            then:
             - deep_sleep.enter: deep_sleep_control

  - platform: gpio
    pin: GPIO8
    id: status_led
    name: "Status"
    restore_mode: ALWAYS_OFF
    inverted: true
    internal: true
            
  - platform: template
    id: deep_sleep_checker
    name: "Stay Awake!"
    optimistic: true
    assumed_state: true
    restore_mode: ALWAYS_ON
    
sensor:
  - platform: adc
    pin: GPIO1
    # id: lm35_adc
    id: "temperature"
    attenuation: 0db
    accuracy_decimals: 1
    name: "Temperature"
    icon: "mdi:thermometer"
    unit_of_measurement: "°C"
    state_class: "measurement"
    update_interval: never
    filters:
      - sliding_window_moving_average:
          window_size: 50
          send_every: 50
          send_first_at: 50
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0 -> 0
          - 1 -> 100
    on_value: 
      then:
        - switch.turn_off: lm35_power

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    bssid:
      name: "BSSID"
